# 集群名
clusterName: "cluster-production"

image:
  repository: "apache/rocketmq"
  tag: "4.9.7"

broker:
  # 3个 master 节点，每个 master 具有1个副节点，共6个 broker 节点
  size:
    master: 3
    replica: 1

  persistence:
    enabled: true
    size: 20Gi
    #storageClass: gp2

  # 主节点资源分配
  master:
    brokerRole: ASYNC_MASTER
    jvmMemory: "-Xms4g -Xmx4g"
    resources:
      limits:
        cpu: 4
        memory: 16Gi
      requests:
        cpu: 500m
        memory: 8Gi
  
  # 副节点资源分配
  replica:
    jvmMemory: "-Xms2g -Xmx2g"
    resources:
      limits:
        cpu: 4
        memory: 16Gi
      requests:
        cpu: 100m
        memory: 4Gi

nameserver:
  replicaCount: 3

  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 50m
      memory: 1Gi

dashboard:
  enabled: true
  replicaCount: 1

  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: rocketmq-dashboard.example.com
    tls: []
    #  - secretName: example-tls
    #    hosts:
    #      - rocketmq-dashboard.example.com
