apiVersion: v2
name: rocketmq
description: RocketMQ Helm chart
type: application

version: 2.2.0
appVersion: '4.9.7'

maintainers:
  - name: itboon
    url: 'https://github.com/itboon/rocketmq-helm'

keywords:
  - rocketmq
  - kubernetes
  - apache